### ISSUE TITLE
Java Magazine Trains

### ISSUE THREAD

**Issue by sheosatyam** [TFaga/kumuluzee-examples#1]
Hi Tilen,

I was trying the Magazine Train sample. I am able to invoke the routes and booking URLs successfully. I am stuck with /faces/index.xhtml URL though which gives me HTTP 503 Error (Problem accessing /faces/index.xhtml Reason: Service Unavailable).

I am running this on Windows 7 machine with no changes to the sample code base.

Regards,
Sheo

**Comment by lathspell** [comment]
Same problem here, the Service Unavailble is caused by a crash of the Faces servlet.

```
chammers@sys-251:~/workspace/kumuluzee-examples/java-magazine-trains/ui$ mvn exec:java -Dexec.mainClass=com.kumuluz.ee.EeApplication
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Java Magazine KumuluzEE Docker with Zookeeper UI 2.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) > validate @ java-magazine-trains-ui >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) < validate @ java-magazine-trains-ui <<<
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ java-magazine-trains-ui ---
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication initialize
INFO: Initializing KumuluzEE
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication initialize
INFO: Checking for requirements
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication initialize
INFO: Checks passed
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication initialize
INFO: Initializing components
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.loaders.ServerLoader loadServletServer
INFO: Loading the KumuluzEE server...
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.loaders.ServerLoader loadServletServer
INFO: Found Jetty
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.loaders.ComponentLoader loadComponents
INFO: Loading available components
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.loaders.ComponentLoader loadComponents
INFO: Loading for components complete
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication processEeComponents
INFO: Processing EE component dependencies
6 [com.kumuluz.ee.EeApplication.main()] INFO org.eclipse.jetty.util.log - Logging initialized @2703ms
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.jetty.JettyFactory createThreadPool
INFO: Starting KumuluzEE on Jetty with 5 minimum and 100 maximum threads
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.jetty.JettyFactory createConnector
INFO: Starting KumuluzEE on port 8080
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.jetty.JettyServletServer initWebContext
INFO: Starting KumuluzEE with context root '/'
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication initialize
INFO: Found EE component JAX-RS implemented by Jersey
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.jaxrs.JaxRsComponent load
INFO: Initiating Jersey
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication initialize
INFO: Found EE component CDI implemented by Weld
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.cdi.CdiComponent load
INFO: Initiating Weld
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication initialize
INFO: Found EE component JPA implemented by EclipseLink
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.jpa.JpaComponent load
INFO: Initiating EclipseLink
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication initialize
INFO: Found EE component EL implemented by UEL
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.el.ElComponent load
INFO: Initiating UEL
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication initialize
INFO: Found EE component JSF implemented by Mojarra
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.jsf.mojarra.JsfComponent load
INFO: Initiating Mojarra
Apr 25, 2016 6:46:30 PM com.kumuluz.ee.EeApplication initialize
INFO: Components initialized
101 [com.kumuluz.ee.EeApplication.main()] INFO org.eclipse.jetty.server.Server - jetty-9.3.7.v20160115
2016-04-25 18:46:30 INFO  servletWeldServlet:57 - WELD-ENV-001008: Initialize Weld using ServletContainerInitializer
2016-04-25 18:46:30 INFO  Version:153 - WELD-000900: 2.3.3 (Final)
2016-04-25 18:46:31 INFO  Bootstrap:45 - WELD-ENV-000020: Using jandex for bean discovery
2016-04-25 18:46:31 INFO  Bootstrap:209 - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
2016-04-25 18:46:31 INFO  Event:87 - WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2016-04-25 18:46:31 INFO  servletJetty:77 - WELD-ENV-001200: Jetty 7.2+ detected, CDI injection will be available in Servlets and Filters. Injection into Listeners should work on Jetty 9.1.1 and newer.
Apr 25, 2016 6:46:31 PM javax.faces.FactoryFinderInstance copyInjectionProviderFromFacesContext
SEVERE: Unable to obtain InjectionProvider from init time FacesContext. Does this container implement the Mojarra Injection SPI?
Apr 25, 2016 6:46:31 PM javax.faces.FactoryFinderInstance getFactory
SEVERE: Application was not properly initialized at startup, could not find Factory: javax.faces.context.FacesContextFactory. Attempting to find backup.
1217 [com.kumuluz.ee.EeApplication.main()] WARN / - unavailable
java.lang.IllegalStateException: Could not find backup for factory javax.faces.context.FacesContextFactory. 
        at javax.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:555)
        at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:283)
        at javax.faces.webapp.FacesServlet.init(FacesServlet.java:358)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:640)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:419)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:875)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:350)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1379)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1341)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:263)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:405)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:372)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.kumuluz.ee.jetty.JettyServletServer.startServer(JettyServletServer.java:52)
        at com.kumuluz.ee.EeApplication.initialize(EeApplication.java:99)
        at com.kumuluz.ee.EeApplication.<init>(EeApplication.java:41)
        at com.kumuluz.ee.EeApplication.main(EeApplication.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:745)
1219 [com.kumuluz.ee.EeApplication.main()] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@514f1c86{/,file:///home/chammers/workspace/kumuluzee-examples/java-magazine-trains/ui/target/classes/webapp/,STARTING}
javax.servlet.ServletException: Faces Servlet@87ee159b==javax.faces.webapp.FacesServlet,1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:661)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:419)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:875)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:350)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1379)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1341)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:263)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:405)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:372)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.kumuluz.ee.jetty.JettyServletServer.startServer(JettyServletServer.java:52)
        at com.kumuluz.ee.EeApplication.initialize(EeApplication.java:99)
        at com.kumuluz.ee.EeApplication.<init>(EeApplication.java:41)
        at com.kumuluz.ee.EeApplication.main(EeApplication.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Could not find backup for factory javax.faces.context.FacesContextFactory. 
        at javax.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:555)
        at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:283)
        at javax.faces.webapp.FacesServlet.init(FacesServlet.java:358)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:640)
        ... 25 more
1231 [com.kumuluz.ee.EeApplication.main()] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@119dec0f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
1231 [com.kumuluz.ee.EeApplication.main()] INFO org.eclipse.jetty.server.Server - Started @3930ms
Apr 25, 2016 6:46:31 PM com.kumuluz.ee.EeApplication initialize
INFO: KumuluzEE started successfully
^C19538 [Thread-1] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@119dec0f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
19562 [Thread-1] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@514f1c86{/,file:///home/chammers/workspace/kumuluzee-examples/java-magazine-trains/ui/target/classes/webapp/,UNAVAILABLE}

```

Using "mvn dependency:copy-dependencies" I see that the javax.faces.jar is on the classpath and that there is no conflicting implementation like e.g. myfaces:

```

chammers@sys-251:~/workspace/kumuluzee-examples/java-magazine-trains/ui$ find target/dependency/ | egrep -i '(faces|jsf|mojarra)'
target/dependency/jsf-api-2.2.12.jar
target/dependency/kumuluzee-jsf-mojarra-2.1.0-SNAPSHOT.jar
target/dependency/javax.faces-2.2.12.jar
target/dependency/weld-core-jsf-2.3.3.Final.jar

```

The problem occurs with kumuluzee 2.0.0, 2.1.0-beta.1 and 2.1.0-SNAPSHOT and also when starting with the documented: 

```
java -cp target/classes:target/dependency/* com.kumuluz.ee.EeApplication
```

I'm running Java 1.8.0_72 and build with Maven 3.3.9.

**Comment by publinchi** [comment]
Solution:

https://github.com/TFaga/kumuluzee-examples/pull/2/commits/89c675e10b898317eb3fbf10d5f65cc8c9d4b36a
